# Generated by Django 5.1.3 on 2024-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='deadline_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
