# Generated by Django 5.1.3 on 2024-12-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_leavemodel_end_leave_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='end_leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='start_leave_date',
            field=models.DateField(),
        ),
    ]
