# Generated by Django 5.1.3 on 2024-12-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_leavemodel_end_leave_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='end_leave_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='start_leave_date',
            field=models.CharField(max_length=50),
        ),
    ]
